name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up variables
      id: vars
      run: echo "IMAGE_TAG=username/app_py311:$(date +%s)" >> $GITHUB_ENV


    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push $IMAGE_TAG
